#
# ansible-playbook  -i ./hosts ./rhel8_cockpit.yaml  -e @./secrets.yaml
# 
---
- hosts: cockpit_demo
  become: True
  become_user: root
  vars:
    ansible_user: ec2-user
  tasks:

  - name: Install the cockpit software and dependancies
    yum: name={{item}} state=present
    with_items :
     - cockpit

  - name: Cockpit needs to be running
    systemd:
      name: cockpit
      state: started
      enabled: yes
      masked: no

  - name: Add additional demo dependancies for virtual machine management
    yum: name={{item}} state=present
    with_items :
     - cockpit-machines
     - virt-viewer

  - name: Install Image Builder and enable for Cockpit
    yum: name={{item}} state=present
    with_items :
     - lorax-composer
     - composer-cli
     - cockpit-composer
     - bash-completion

  - name: Additional Image Builder service
    systemd:
      name: "{{item}}"
      state: started
      enabled: yes
      masked: no
    with_items:
     - 'lorax-composer.socket'
     - 'cockpit.socket'


  - name: Change the password for the root user
    user:
      name: root
      password: "{{cockpit_root_pw}}"

  #- name: Firewalld
    #firewalld:
      #service: cockpit
      #immediate: true
      #permanent: true
      #state: enabled
