#
# Example execution
# ansible-playbook  -e @secrets.yaml ./terminate_cockpit.yaml 
#

- hosts: localhost
  gather_facts: False

  vars:
    region: us-east-2
    demo_tag: cockpit

  tasks:
  - name: Terminate tagged instances
    ec2_instance:
      state: absent
      region: "{{ region }}"
      filters:
        tag:Demo: "{{demo_tag}}"
